import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/home1">Home1</Link>
        </li>
        <li>
          <Link to="/master">Master</Link>
        </li>
        <li>
          <Link to="/mastercountry">MasterCountry</Link>
        </li>
        <li>
          <Link to="/mastercity">MasterCity</Link>
        </li>
        <li>
          <Link to="/masterunit">MasterUnit</Link>
        </li>
        <li>
          <Link to="/mastervat">MasterVAT</Link>
        </li>
        <li>
          <Link to="/masteremployees">MasterEmployees</Link>
        </li>
        <li>
          <Link to="/mastercurrency">MasterCurrency</Link>
        </li>
        <li>
          <Link to="/mastercurrencyconvertion">MasterCurrencyConvertion</Link>
        </li>
        <li>
          <Link to="/mastercustomer">MasterCustomer</Link>
        </li>
        <li>
          <Link to="/mastercustomerupload">MasterCustomerUpload</Link>
        </li>
        <li>
          <Link to="/mastervendors">MasterVendors</Link>
        </li>
        <li>
          <Link to="/masterexpenses">MasterExpenses</Link>
        </li>
        <li>
          <Link to="/masteraccounttypes">MasterAccountTypes</Link>
        </li>
        <li>
          <Link to="/masteraccounttypestwo">MasterAccountTypesTwo</Link>
        </li>
        <li>
          <Link to="/masterchartsofaccounts">MasterChartsofAccounts</Link>
        </li>
        <li>
          <Link to="/masterchartsofaccountstwo">MasterChartsofAccountsTwo</Link>
        </li>
        <li>
          <Link to="/masterchartsofaccountsthree">
            MasterChartsofAccountsThree
          </Link>
        </li>
        <li>
          <Link to="/mastercostcenter">MasterCostCenter</Link>
        </li>
        <li>
          <Link to="/mastercostcentertwo">MasterCostCenterTwo</Link>
        </li>
        <li>
          <Link to="/masterproducts">MasterProducts</Link>
        </li>
        <li>
          <Link to="/masterproductlist">MasterProductList</Link>
        </li>
        <li>
          <Link to="/masterassetlist">MasterAssetList</Link>
        </li>
        <li>
          <Link to="/masterservicelist">MasterServiceList</Link>
        </li>
        <li>
          <Link to="/masterproductupload">MasterProductUpload</Link>
        </li>
        <li>
          <Link to="/masterproductupdate">MasterProductUpdate</Link>
        </li>
        <li>
          <Link to="/masterservices">MasterServices</Link>
        </li>
        <li>
          <Link to="/masterassts">MasterAssts</Link>
        </li>
        <li>
          <Link to="/masterproducttypes">MasterProductTypes</Link>
        </li>
        <li>
          <Link to="/masterproductcolors">MasterProductColors</Link>
        </li>
        <li>
          <Link to="/masteruserpagerole">MasterUserPageRole</Link>
        </li>
        <li>
          <Link to="/masteruserbuttonrole">MasterUserButtonRole</Link>
        </li>
        <li>
          <Link to="/mastervoucherdocs">MasterVoucherDocs</Link>
        </li>
        <li>
          <Link to="/purchase">Purchase</Link>
        </li>
        <li>
          <Link to="/purchasepurchaserequest">PurchasePurchaseRequest</Link>
        </li>
        <li>
          <Link to="/purchasepurchasequotation">PurchasePurchaseQuotation</Link>
        </li>
        <li>
          <Link to="/purchasepurchaseorder">PurchasePurchaseOrder</Link>
        </li>
        <li>
          <Link to="/purchasegoodsreceived">PurchaseGoodsreceived</Link>
        </li>
        <li>
          <Link to="/purchasepurchaseinvoice">PurchasePurchaseinvoice</Link>
        </li>
        <li>
          <Link to="/purchasepurchasereturn">PurchasePurchasereturn</Link>
        </li>
        <li>
          <Link to="/sales">Sales</Link>
        </li>
        <li>
          <Link to="/salessalesenquiry">SalessalesEnquiry</Link>
        </li>
        <li>
          <Link to="/salessalesquotation">SalesSalesQuotation</Link>
        </li>
        <li>
          <Link to="/salessalesorder">SalesSalesOrder</Link>
        </li>
        <li>
          <Link to="/salesdeliverynote">SalesDeliveryNote</Link>
        </li>
        <li>
          <Link to="/salessalesinvoice">SalesSalesInvoice</Link>
        </li>
        <li>
          <Link to="/salessalesreturn">SalesSalesReturn</Link>
        </li>
        <li>
          <Link to="/salesalrawanfoodstufftrading">
            SalesAlRawanFoodstuffTrading
          </Link>
        </li>
        <li>
          <Link to="/salesdistinguishedagentfortechnicalservices">
            SalesDistinguishedagentfortechnicalservices
          </Link>
        </li>
        <li>
          <Link to="/salesmanaratalshamvegetableandfruittradingllc">
            SalesManaratAlShamVegetableandFruitTradingLLC
          </Link>
        </li>
        <li>
          <Link to="/salesmanarathouranfoodstufftradingllc">
            SalesManaratHouranFoodstuffTradingLLC
          </Link>
        </li>
        <li>
          <Link to="/salesoscarvegetablesandfruitsllc">
            SalesOscarVegetablesandFruitsLLC
          </Link>
        </li>
        <li>
          <Link to="/basicvouchers">BasicVouchers</Link>
        </li>
        <li>
          <Link to="/basicvouchersinitialbalance">
            BasicVouchersInitialBalance
          </Link>
        </li>
        <li>
          <Link to="/basicvouchersdailycoupon">BasicVouchersDailycoupon</Link>
        </li>
        <li>
          <Link to="/basicvoucherscompanyexpenses">
            BasicVouchersCompanyexpenses
          </Link>
        </li>
        <li>
          <Link to="/paymentvouchers">PaymentVouchers</Link>
        </li>
        <li>
          <Link to="/paymentvoucherscashpayment">
            PaymentVouchersCashPayment
          </Link>
        </li>
        <li>
          <Link to="/paymentvouchersfundpaymentvoucher">
            PaymentVouchersFundPaymentVoucher
          </Link>
        </li>
        <li>
          <Link to="/paymentvouchersverifypaymentvoucher">
            PaymentVouchersVerifyPaymentVoucher
          </Link>
        </li>
        <li>
          <Link to="/receiptvouchers">ReceiptVouchers</Link>
        </li>
        <li>
          <Link to="/receiptvoucherscashreceipt">
            ReceiptVouchersCashReceipt
          </Link>
        </li>
        <li>
          <Link to="/receiptvouchersfundreceipt">
            ReceiptVouchersFundReceipt
          </Link>
        </li>
        <li>
          <Link to="/receiptvoucherschequereceipt">
            ReceiptVouchersChequeReceipt
          </Link>
        </li>
        <li>
          <Link to="/pdcmanagemennt">PDCManagemennt</Link>
        </li>
        <li>
          <Link to="/pdcmanagemenntpendingpdcs">PDCManagemenntPendingPDCs</Link>
        </li>
        <li>
          <Link to="/pdcmanagemenntprocessedpdcs">
            PDCManagemenntProcessedPDCs
          </Link>
        </li>
        <li>
          <Link to="/pdcmanagemenntreconcilechequepayment">
            PDCManagemenntReconcileChequePayment
          </Link>
        </li>
        <li>
          <Link to="/pdcmanagemenntreconcilechequereceipt">
            PDCManagemenntReconcileChequeReceipt
          </Link>
        </li>
        <li>
          <Link to="/stocks">Stocks</Link>
        </li>
        <li>
          <Link to="/stocksopeningstocks">StocksOpeningStocks</Link>
        </li>
        <li>
          <Link to="/stocksstockissue">StocksStockIssue</Link>
        </li>
        <li>
          <Link to="/stocksstockreceive">StocksStockReceive</Link>
        </li>
        <li>
          <Link to="/page">Page</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
